"use client";

import { useDashboardStore } from "@/stores/dashboardStore";
import { cn } from "@/lib/utils";

/**
 * NarrativeCard (PR-2 Tier-1)
 *
 * Reads the persisted `narrative` slot from the Firestore `market_brain/latest`
 * doc (surfaced into the store by `useMarketBrain`). The narrative is generated
 * server-side by `MarketBrainService.build_narrative` so there is a single
 * canonical phrasing shared by BE telemetry, voice alerts, and this card.
 *
 * The card renders three buckets — drivers / risks / opportunities — in a
 * colour-coded grid, with the headline + supporting sentences on top. When
 * the narrative is missing (older Firestore docs, pre-PR-2 deploys) we render
 * a quiet placeholder so the page still composes cleanly.
 */
export function NarrativeCard() {
  const narrative = useDashboardStore((s) => s.brainNarrative);
  const brain = useDashboardStore((s) => s.marketBrain);

  if (!narrative) {
    return (
      <div className="bg-bg-secondary rounded-lg border border-bg-tertiary p-5">
        <div className="flex items-center justify-between mb-2">
          <h3 className="text-sm font-medium text-text-primary">Market Narrative</h3>
          <span className="text-[10px] text-text-secondary">awaiting next brain run</span>
        </div>
        <p className="text-xs text-text-secondary italic">
          Narrative becomes available once the brain emits a post-PR-2 snapshot.
        </p>
      </div>
    );
  }

  const sentences = narrative.sentences?.filter((s) => s?.trim().length > 0) ?? [];
  const drivers = narrative.key_drivers ?? [];
  const risks = narrative.risks ?? [];
  const opportunities = narrative.opportunities ?? [];

  return (
    <div className="bg-bg-secondary rounded-lg border border-bg-tertiary p-5">
      <div className="flex items-center justify-between mb-2">
        <h3 className="text-sm font-medium text-text-primary">Market Narrative</h3>
        {brain?.run_degraded_flag && (
          <span
            className="text-[10px] font-semibold px-1.5 py-0.5 rounded bg-loss/20 text-loss"
            title="Narrative generated from a degraded run — signals may be incomplete."
          >
            DEGRADED
          </span>
        )}
      </div>

      {/* Headline */}
      <p className="text-base font-semibold text-text-primary leading-snug mb-2">
        {narrative.headline}
      </p>

      {/* Supporting sentences */}
      {sentences.length > 0 && (
        <div className="space-y-1 mb-4">
          {sentences.map((s, i) => (
            <p key={i} className="text-xs text-text-secondary leading-relaxed">
              {s}
            </p>
          ))}
        </div>
      )}

      {/* Three-bucket grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
        <NarrativeList
          title="Key drivers"
          items={drivers}
          accent="#3b82f6"
          empty="No standout drivers."
        />
        <NarrativeList
          title="Risks"
          items={risks}
          accent="#ef4444"
          empty="No acute risks flagged."
        />
        <NarrativeList
          title="Opportunities"
          items={opportunities}
          accent="#22c55e"
          empty="No clear opportunities today."
        />
      </div>

      <p className="text-[10px] text-text-secondary text-right mt-3 opacity-70">
        Generated by brain @ {narrative.as_of ? new Date(narrative.as_of).toLocaleTimeString() : "—"}
      </p>
    </div>
  );
}

function NarrativeList({
  title,
  items,
  accent,
  empty,
}: {
  title: string;
  items: string[];
  accent: string;
  empty: string;
}) {
  return (
    <div className="bg-bg-primary rounded-md p-3 min-w-0" style={{ borderTop: `2px solid ${accent}` }}>
      <p className="text-[10px] font-semibold uppercase tracking-wider mb-1.5" style={{ color: accent }}>
        {title}
      </p>
      {items.length === 0 ? (
        <p className="text-[11px] text-text-secondary italic">{empty}</p>
      ) : (
        <ul className="space-y-1">
          {items.map((item, i) => (
            <li
              key={i}
              className={cn("text-[11px] text-text-primary leading-relaxed pl-2 relative")}
              style={{ borderLeft: `1px solid ${accent}30` }}
            >
              <span className="pl-1">{item}</span>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
