"""Auto-generated by scripts/redesign/calibrate_slippage.py.

# slippage calibration over 73 valid fills (input=73)
#   fitted: BarRangePct(pct_of_range=0.0000, cap_bps=10.00, floor_bps=0.50)
#   median pct_of_range: 0.0000
#   adverse bps: median=0.00, p95=10.00, max=10.09
#   confidence: high
"""
from autotrader.backtest.slippage import BarRangePct


def calibrated_slippage() -> BarRangePct:
    return BarRangePct(pct_of_range=0.0, cap_bps=10.0, floor_bps=0.5)
