#!/usr/bin/env python3
"""Calibrate `BarRangePct` slippage parameters against real fills.

Pulls (trade, scan_decision, 5m bar) joins from BigQuery and fits the
`pct_of_range` / `cap_bps` / `floor_bps` parameters to match what the
broker actually delivered. Run weekly to keep the sim's P&L magnitudes
honest.

Examples
--------

    # Default — calibrate over the last 4 weeks
    python scripts/redesign/calibrate_slippage.py \\
        --project grow-profit-machine --dataset autotrader \\
        --since 2026-04-08 --until 2026-05-04

    # Wider match window if your scanner-to-fill latency is noisier
    python scripts/redesign/calibrate_slippage.py \\
        --project grow-profit-machine --dataset autotrader \\
        --since 2026-04-16 --until 2026-05-04 \\
        --match-window-seconds 180

Output
------
Prints the fitted model + diagnostic stats. Use the printed
`BarRangePct(...)` line directly in code or pass `--write-py PATH` to
emit a Python module that imports cleanly.
"""
from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path


def _setup_path() -> None:
    sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "src"))


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s %(message)s",
    )
    ap = argparse.ArgumentParser(prog="calibrate-slippage", description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--project", default="grow-profit-machine")
    ap.add_argument("--dataset", default="autotrader")
    ap.add_argument("--since", required=True, help="YYYY-MM-DD inclusive")
    ap.add_argument("--until", required=True, help="YYYY-MM-DD inclusive")
    ap.add_argument("--match-window-seconds", type=int, default=90,
                    help="max seconds between scan_ts and entry_ts to consider matched")
    ap.add_argument("--write-py", default=None,
                    help="if set, write a Python module at this path defining "
                         "`calibrated_slippage()` returning the fitted model")
    ap.add_argument("--write-json", default=None,
                    help="if set, write the raw metrics dict to this path")
    args = ap.parse_args(argv)

    _setup_path()

    from autotrader.backtest.slippage_calibration import (
        calibrate_from_fills,
        load_calibration_data,
    )

    fills = load_calibration_data(
        project=args.project, dataset=args.dataset,
        since=args.since, until=args.until,
        match_window_seconds=args.match_window_seconds,
    )
    print(f"loaded {len(fills)} fill observations from BQ")

    result = calibrate_from_fills(fills)
    print()
    print("─" * 64)
    print("  SLIPPAGE CALIBRATION")
    print("─" * 64)
    print(result.summary)
    print("─" * 64)
    print()
    m = result.model  # type: ignore[union-attr]
    print(f"  drop-in: BarRangePct(pct_of_range={m.pct_of_range}, "  # type: ignore[attr-defined]
          f"cap_bps={m.cap_bps}, floor_bps={m.floor_bps})")  # type: ignore[attr-defined]

    if args.write_py:
        path = Path(args.write_py)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(_render_py_module(m, result.summary))
        print(f"\nwrote calibrated module → {path}")

    if args.write_json:
        path = Path(args.write_json)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps({
            "model": {
                "pct_of_range": m.pct_of_range,  # type: ignore[attr-defined]
                "cap_bps": m.cap_bps,            # type: ignore[attr-defined]
                "floor_bps": m.floor_bps,         # type: ignore[attr-defined]
            },
            "n_fills": result.n_fills,
            "confidence": result.confidence,
            **result.raw_metrics,
        }, indent=2, sort_keys=True))
        print(f"wrote metrics JSON → {path}")

    # Exit 0 unless we couldn't calibrate at all
    return 0 if result.confidence != "low" or result.n_fills > 0 else 1


def _render_py_module(model, summary: str) -> str:
    summary_indented = "\n".join(f"# {line}" for line in summary.splitlines())
    return (
        '"""Auto-generated by scripts/redesign/calibrate_slippage.py.\n\n'
        + summary_indented + '\n"""\n'
        + "from autotrader.backtest.slippage import BarRangePct\n\n\n"
        + "def calibrated_slippage() -> BarRangePct:\n"
        + f"    return BarRangePct(pct_of_range={model.pct_of_range}, "
        + f"cap_bps={model.cap_bps}, floor_bps={model.floor_bps})\n"
    )


if __name__ == "__main__":
    sys.exit(main())
