#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 6 ]]; then
  echo "Usage: $0 <PROJECT_ID> <REGION> <SERVICE_NAME> <IMAGE> <SHEET_ID> <BUCKET>"
  echo "Requires env: JOB_TRIGGER_TOKEN"
  exit 1
fi

PROJECT_ID="$1"
REGION="$2"
SERVICE_NAME="$3"
IMAGE="$4"
SHEET_ID="$5"
BUCKET="$6"

if [[ -z "${JOB_TRIGGER_TOKEN:-}" ]]; then
  echo "ERROR: JOB_TRIGGER_TOKEN env var is required."
  echo "Export it first, then rerun deploy."
  exit 1
fi

# Required secret-name envs (AppSettings.from_env hard requirements).
GROWW_API_KEY_SECRET_NAME="${GROWW_API_KEY_SECRET_NAME:-groww-api-key}"
GROWW_API_SECRET_SECRET_NAME="${GROWW_API_SECRET_SECRET_NAME:-groww-api-secret}"
GROWW_ACCESS_TOKEN_SECRET_NAME="${GROWW_ACCESS_TOKEN_SECRET_NAME:-groww-access-token}"
GROWW_ACCESS_TOKEN_EXPIRY_SECRET_NAME="${GROWW_ACCESS_TOKEN_EXPIRY_SECRET_NAME:-groww-access-token-expiry}"
UPSTOX_CLIENT_ID_SECRET_NAME="${UPSTOX_CLIENT_ID_SECRET_NAME:-upstox-client-id}"
UPSTOX_CLIENT_SECRET_SECRET_NAME="${UPSTOX_CLIENT_SECRET_SECRET_NAME:-upstox-client-secret}"
UPSTOX_ACCESS_TOKEN_SECRET_NAME="${UPSTOX_ACCESS_TOKEN_SECRET_NAME:-upstox-access-token}"
UPSTOX_ACCESS_TOKEN_EXPIRY_SECRET_NAME="${UPSTOX_ACCESS_TOKEN_EXPIRY_SECRET_NAME:-upstox-access-token-expiry}"
UPSTOX_AUTH_CODE_SECRET_NAME="${UPSTOX_AUTH_CODE_SECRET_NAME:-upstox-auth-code}"

ENV_VARS=(
  "GCP_PROJECT_ID=$PROJECT_ID"
  "GCP_REGION=$REGION"
  "GOOGLE_SHEETS_SPREADSHEET_ID=$SHEET_ID"
  "GCS_BUCKET=$BUCKET"
  "FIRESTORE_DATABASE=${FIRESTORE_DATABASE:-(default)}"
  "UPSTOX_API_V2_HOST=${UPSTOX_API_V2_HOST:-https://api.upstox.com/v2}"
  "UPSTOX_API_V3_HOST=${UPSTOX_API_V3_HOST:-https://api.upstox.com/v3}"
  "UPSTOX_REQUESTS_PER_SECOND=${UPSTOX_REQUESTS_PER_SECOND:-50}"
  "UPSTOX_MAX_PER_MINUTE=${UPSTOX_MAX_PER_MINUTE:-500}"
  "UPSTOX_MAX_PER_30MIN=${UPSTOX_MAX_PER_30MIN:-2000}"
  "UPSTOX_MAX_RETRIES=${UPSTOX_MAX_RETRIES:-4}"
  "UPSTOX_CLIENT_ID_SECRET_NAME=$UPSTOX_CLIENT_ID_SECRET_NAME"
  "UPSTOX_CLIENT_SECRET_SECRET_NAME=$UPSTOX_CLIENT_SECRET_SECRET_NAME"
  "UPSTOX_ACCESS_TOKEN_SECRET_NAME=$UPSTOX_ACCESS_TOKEN_SECRET_NAME"
  "UPSTOX_ACCESS_TOKEN_EXPIRY_SECRET_NAME=$UPSTOX_ACCESS_TOKEN_EXPIRY_SECRET_NAME"
  "UPSTOX_AUTH_CODE_SECRET_NAME=$UPSTOX_AUTH_CODE_SECRET_NAME"
  "UPSTOX_NIFTY50_INSTRUMENT_KEY=${UPSTOX_NIFTY50_INSTRUMENT_KEY:-NSE_INDEX|Nifty 50}"
  "UPSTOX_INDIA_VIX_INSTRUMENT_KEY=${UPSTOX_INDIA_VIX_INSTRUMENT_KEY:-NSE_INDEX|India VIX}"
  "UPSTOX_PCR_UNDERLYING_INSTRUMENT_KEY=${UPSTOX_PCR_UNDERLYING_INSTRUMENT_KEY:-NSE_INDEX|Nifty 50}"
  "GROWW_API_HOST=${GROWW_API_HOST:-https://api.groww.in}"
  "GROWW_API_KEY_SECRET_NAME=$GROWW_API_KEY_SECRET_NAME"
  "GROWW_API_SECRET_SECRET_NAME=$GROWW_API_SECRET_SECRET_NAME"
  "GROWW_ACCESS_TOKEN_SECRET_NAME=$GROWW_ACCESS_TOKEN_SECRET_NAME"
  "GROWW_ACCESS_TOKEN_EXPIRY_SECRET_NAME=$GROWW_ACCESS_TOKEN_EXPIRY_SECRET_NAME"
  "PAPER_TRADE=${PAPER_TRADE:-true}"
  "JOB_TRIGGER_TOKEN=$JOB_TRIGGER_TOKEN"
  "LOG_LEVEL=${LOG_LEVEL:-INFO}"
  "TZ=${TZ:-Asia/Kolkata}"
)

if [[ -n "${UPSTOX_REDIRECT_URI:-}" ]]; then
  ENV_VARS+=("UPSTOX_REDIRECT_URI=$UPSTOX_REDIRECT_URI")
fi
if [[ -n "${UPSTOX_NOTIFIER_SHARED_SECRET:-}" ]]; then
  ENV_VARS+=("UPSTOX_NOTIFIER_SHARED_SECRET=$UPSTOX_NOTIFIER_SHARED_SECRET")
fi

ENV_VARS_CSV="$(IFS=,; echo "${ENV_VARS[*]}")"

gcloud run deploy "$SERVICE_NAME" \
  --project "$PROJECT_ID" \
  --region "$REGION" \
  --image "$IMAGE" \
  --platform managed \
  --allow-unauthenticated \
  --port 8080 \
  --cpu 1 \
  --memory 1Gi \
  --min-instances 0 \
  --max-instances 3 \
  --timeout 3600 \
  --concurrency 20 \
  --update-env-vars "$ENV_VARS_CSV"

echo "Cloud Run service deployed."
